In [1]:

3+5

8

In [2]:
10-4

6

In [3]:
7*6

42

In [5]:
12+15

27

In [6]:
100-45

55

In [7]:
9*8

72

In [8]:
144/12

12.0

In [12]:
5**3

125

In [10]:
import math


In [11]:
math.cos(2 * math.pi)

1.0

In [13]:
name = "Alice"
print(name)
print(type(name))

Alice
<class 'str'>


In [14]:
age = 25
print(age)
print(type(age))

25
<class 'int'>


In [15]:
name="Bareaa"
age=19
height=1.70
print(name)
print(age)
print(height)
print(type(name))
print(type(age))
print(type(height))

Bareaa
19
1.7
<class 'str'>
<class 'int'>
<class 'float'>


In [17]:
""" i am trying to test 
out the jupyter lab"""


' i am trying to test \nout the jupyter lab'

In [21]:
print(f"pi is approximately equatl to {math.pi}")

pi is approximately equatl to 3.141592653589793


In [25]:
favcolors=["pink","dark red","ivy green"]
print(favcolors)
favcolors.append("dark blue")
print(favcolors)
favcolors.remove("pink")
print(favcolors)

['pink', 'dark red', 'ivy green']
['pink', 'dark red', 'ivy green', 'dark blue']
['dark red', 'ivy green', 'dark blue']


In [26]:
favcolors=["pink","dark red","ivy green","dark blue", "baby blue"]
print(favcolors[1])
print(favcolors[3])
print(favcolors[-1])
favcolors[2]="baby pink"
print(favcolors)

dark red
dark blue
baby blue
['pink', 'dark red', 'baby pink', 'dark blue', 'baby blue']


In [31]:
list_var = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
print(list_var[1][0:2])
print(list_var[1][-1])
print(list_var[2][1])

[4, 5]
6
8


In [34]:
number = 5

if number%2== 0:
    print("The number is even.")
else:
    print("the number is odd")
    

the number is odd


In [35]:
number = 0

if number%2== 0:
    print("The number is even.")
else:
    print("the number is odd")

The number is even.


In [36]:
number = 10

if number%2== 0:
    print("The number is even.")
else:
    print("the number is odd")

The number is even.


In [47]:
i=0

for idx, x in enumerate(["scientific", "computing", "with", "python"]):
       print(f"item {idx} is {x}")
  

item 0 is scientific
item 1 is computing
item 2 is with
item 3 is python


In [49]:
def power(s):
    print(s**2,s**3,s**4)

power(3)

9 27 81


In [50]:

import numpy as np


In [51]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)

print("List:", my_list)
print("NumPy Array:", my_array)


List: [1, 2, 3, 4]
NumPy Array: [1 2 3 4]


In [55]:
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print("List Addition (Concatenation):", list1 + list2)

array1= np.array(list1)
array2= np.array(list2)

print("Array Addition:", array1 + array2)  # Element-wise addition
print("Array Multiplication:", array1 * array2)  
print(array1*2)


List Addition (Concatenation): [1, 2, 3, 1, 2, 3]
Array Addition: [2 4 6]
Array Multiplication: [1 4 9]
[2 4 6]


# matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)

matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1,2,3]
])
print("Matrix:")
print(matrix1)
print("Shape:", matrix1.shape)

In [56]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)

matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1,2,3]
])

print("Matrix:")
print(matrix1)
print("Shape:", matrix1.shape)

Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Matrix:
[[1 2 3]
 [4 5 6]
 [1 2 3]]
Shape: (3, 3)


In [57]:
mixed_list = [1, 2.5, "hello"]
print("Python List:", mixed_list)

array = np.array([1, 2.5, 3,"hello"])
print("NumPy Array:", array)
print("Array Data Type:", array.dtype)

Python List: [1, 2.5, 'hello']
NumPy Array: ['1' '2.5' '3' 'hello']
Array Data Type: <U32


In [58]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[1][2])
print(matrix[-1][1])
print(matrix[1:,1:])

6
8
[[5 6]
 [8 9]]


In [60]:
class Point:
    """
    Simple class for representing a point in a Cartesian coordinate system.
    """

    def __init__(self, x, y):
        """
        Create a new Point at x, y.
        """
        self.x = x
        self.y = y

    def translate(self, dx, dy):
        """
        Translate the point by dx and dy in the x and y direction.
        """
        self.x += dx
        self.y += dy

    def __str__(self):
        return("Point at [%f, %f]" % (self.x, self.y))
        
p1 = Point(0, 0) # this will invoke the __init__ method in the Point class

p2 = Point(1, 1)

p1.translate(0.25, 1.5)

print(p1)
print(p2)

Point at [0.250000, 1.500000]
Point at [1.000000, 1.000000]


In [61]:
try:
    print(2/0)

except:
    print("cant divide by 0")

cant divide by 0
